export type StudioPoint = Readonly<{ lat: number; lng: number; elevationM?: number }>;
export type ControlPoint = Readonly<{ id: string; lat: number; lng: number; elevationM: number }>;
export type GeometryPoint = Readonly<{ lat: number; lng: number; elevationM: number }>;
export type LegGeometry = Readonly<{ geometry: GeometryPoint[] }>;
export type DraftMetrics = Readonly<{ pointCount: number; distanceM: number; ascentM: number; descentM: number }>;
export type ProfilePoint = Readonly<{ distanceM: number; lat: number; lng: number; elevationM: number }>;
export type DraftSelection = Readonly<{ startM: number; endM: number }>;
export type DraftStatus = "draft" | "ready" | "publishing" | "published";
export type RouteStudioDraft = Readonly<{
  schemaVersion: 2;
  status: DraftStatus;
  revision: number;
  name: string;
  controlPoints: ControlPoint[];
  closedLoop: boolean;
  legResults: Array<GeometryPoint[] | undefined>;
  invalidatedLegIndexes: number[];
  selection: DraftSelection | null;
  historyLimit: number;
  nextControlPointNumber: number;
  undoStack: RouteStudioDraftSnapshot[];
  redoStack: RouteStudioDraftSnapshot[];
}>;
export type RouteStudioDraftSnapshot = Omit<RouteStudioDraft, "undoStack" | "redoStack">;
export type PublishPayload = Readonly<{
  name: string;
  geometry: GeometryPoint[];
  controlPoints: number[];
}>;

export function createDraft(options?: { historyLimit?: number }): RouteStudioDraft;
export function normalizeSegmentName(name: string): string;
export function setDraftName(draft: RouteStudioDraft, name: string): RouteStudioDraft;
export function addControlPoint(draft: RouteStudioDraft, point: StudioPoint): RouteStudioDraft;
export function moveControlPoint(draft: RouteStudioDraft, controlPointId: string, point: StudioPoint): RouteStudioDraft;
export function setControlPointPreview(draft: RouteStudioDraft, controlPointId: string, point: StudioPoint): RouteStudioDraft;
export function removeControlPoint(draft: RouteStudioDraft, controlPointId: string): RouteStudioDraft;
export function reorderControlPoints(draft: RouteStudioDraft, controlPointId: string, targetIndex: number): RouteStudioDraft;
export function setClosedLoop(draft: RouteStudioDraft, closedLoop: boolean): RouteStudioDraft;
export function setLegResult(draft: RouteStudioDraft, legIndex: number, result: LegGeometry): RouteStudioDraft;
export function getComposedGeometry(draft: RouteStudioDraft): GeometryPoint[];
export function getDraftMetrics(draft: RouteStudioDraft): DraftMetrics;
export function trimDraft(draft: RouteStudioDraft, startM: number, endM: number): RouteStudioDraft;
export function resetToFullSelection(draft: RouteStudioDraft): RouteStudioDraft;
export function getTrimmedGeometry(draft: RouteStudioDraft): GeometryPoint[];
export function getSelectionMetrics(draft: RouteStudioDraft): DraftMetrics;
export function getGeometryForRange(draft: RouteStudioDraft, startM: number, endM: number): GeometryPoint[];
export function getMetricsForRange(draft: RouteStudioDraft, startM: number, endM: number): DraftMetrics;
export function getElevationProfile(draft: RouteStudioDraft): ProfilePoint[];
export function lookupProfileAtDistance(draft: RouteStudioDraft, distanceM: number): ProfilePoint | null;
export function prepareDraftForPublication(draft: RouteStudioDraft): RouteStudioDraft;
export function beginDraftPublication(draft: RouteStudioDraft): RouteStudioDraft;
export function failDraftPublication(draft: RouteStudioDraft): RouteStudioDraft;
export function completeDraftPublication(draft: RouteStudioDraft): RouteStudioDraft;
export function resumeDraftEditing(draft: RouteStudioDraft): RouteStudioDraft;
export function undoDraft(draft: RouteStudioDraft): RouteStudioDraft;
export function redoDraft(draft: RouteStudioDraft): RouteStudioDraft;
export function serializeDraft(draft: RouteStudioDraft): string;
export function restoreDraft(serializedDraft: string): RouteStudioDraft;
export function buildPublishPayload(draft: RouteStudioDraft): PublishPayload;
